baseurl:     "" # the subpath of your site, e.g. /blog/
# url:         "http://127.0.0.1:4000/" # the base hostname & protocol for your site
url:         "http://42i.com.br/" # the base hostname & protocol for your site
imgurl:      "/public/images"
destination: ./_site
search:      true
permalink:   /:title/
markdown: kramdown
highlighter: pygments
google_analytics: "UA-41207410-1"
google_verify: ""
typekit_id: "oyt7nbz"
site_name: "42i"
defaults:
  - scope:
      path:  "_posts/pt-br"
    values:
      lang: "pt-br"
      layout: default

  - scope:
      path: "_posts/en"
    values:
      lang: "en"
      layout: default

  - scope:
      path: "_posts/pt-br/pages"
    values:
      type: "pages"
      layout: default

  - scope:
      path: "_posts/en/pages"
    values:
      type: "pages"
      layout: default

  - scope:
      path: "_projects/pt-br/projects"
    values:
      type: "projects"
      lang: "pt-br"
      layout: default

  - scope:
      path: "_projects/en/projects"
    values:
      type: "projects"
      lang: "en"
      layout: default
