# Site settings
baseurl:     "" # the subpath of your site, e.g. /blog/
url:         "http://127.0.0.1:4000/" # the base hostname & protocol for your site
# url:         "http://42ipd.github.io/" # the base hostname & protocol for your site
imgurl:      "/public/images"

destination: ./_site
search:      true
permalink:   /:title/


# Build settings
markdown: kramdown
highlighter: pygments

# Analytics and webmaster tools stuff goes here
google_analytics: ""
google_verify: ""

# Language settings
defaults:
  - scope:
      path:  "_posts/pt-br"
    values:
      lang: "pt-br"
      layout: default

  - scope:
      path: "_posts/en"
    values:
      lang: "en"
      layout: default

  - scope:
      path: "_posts/pt-br/pages"
    values:
      type: "pages"
      layout: default

  - scope:
      path: "_posts/en/pages"
    values:
      type: "pages"
      layout: default

  - scope:
      path: "_projects/pt-br/projects"
    values:
      type: "projects"
      lang: "pt-br"
      layout: default

  - scope:
      path: "_projects/en/projects"
    values:
      type: "projects"
      lang: "en"
      layout: default
