# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url:  "http://localhost:4000" # the base hostname & protocol for your site
imgurl: "http://localhost:4000/public/images"

permalink: /:title/

paginate_path: "blog/page:num"
paginate: 10
destination: "blog/page"

# Build settings
markdown: kramdown
highlighter: pygments

# Language settings
defaults:
  -
    scope:
      path:  ""
    values:
      lang: "pt-br"
      layout: default
  -
    scope:
      path: "_posts/en"
    values:
      lang: "en"
  -
    scope:
      path: "_posts/pt-br/pages"
    values:
      type: "pages"
  -
    scope:
      path: "_posts/en/pages"
    values:
      type: "pages"
