pt-br:
  tech-specs: "Ficha-Técnica"
  project-link: "Link do projeto"
  client: "Cliente"
  year: "Ano"
  project-type: "Tipo"
  platforms: "Plataformas"
  techs: "Tecnologias"
  support: "Suporte"

en:
  tech-specs: "Tech-Specs"
  project-link: "Project link"
  client: "Client"
  year: "Year"
  project-type: "Type"
  platforms: "Platforms"
  support: "Support"
